Save_Load_Status.py: pass dict to exec()
python3 (apparntly) changes the scope of 'exec', variabels defined in
there won't be seen by the caller.
Change from upstream
https://github.com/PyCOMPLETE/PyPARIS_sim_class/blob/master/Save_Load_Status.py

Fixes errors like
NameError: name 'present_simulation_part' is not defined